version: '2'
services:
    peoplecounter-app:
        image: peoplecounter
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://peoplecounter-postgresql:5432/peoplecounter
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    peoplecounter-postgresql:
        extends:
            file: postgresql.yml
            service: peoplecounter-postgresql
