version: '2'
services:
    peoplecounter-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/peoplecounter/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=peoplecounter
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
